services:
  kpi-database:
    image: postgres:13
    container_name: kpi-database
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: kpi-api-database
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app_network
  kpi-automation-api:
    container_name: kpi-automation-api
    image: pedra-pagamentos/kpi-automation-api:1.0.0
    build: .
    ports:
      - "8000:8000"
    environment:
      - DB_URL=postgresql://postgres:admin@kpi-database:5432/kpi-api-database
      - JWT_SECRET_KEY=jwt_secret_key
      - SECRET_KEY=secret_key
    depends_on:
          - kpi-database
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  postgres-data:
